/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { NomadClient } from './NomadClient';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { ACLPolicy } from './models/ACLPolicy';
export type { ACLPolicyListStub } from './models/ACLPolicyListStub';
export type { ACLToken } from './models/ACLToken';
export type { ACLTokenListStub } from './models/ACLTokenListStub';
export type { ACLTokenRoleLink } from './models/ACLTokenRoleLink';
export type { Affinity } from './models/Affinity';
export type { AllocatedCpuResources } from './models/AllocatedCpuResources';
export type { AllocatedDeviceResource } from './models/AllocatedDeviceResource';
export type { AllocatedMemoryResources } from './models/AllocatedMemoryResources';
export type { AllocatedResources } from './models/AllocatedResources';
export type { AllocatedSharedResources } from './models/AllocatedSharedResources';
export type { AllocatedTaskResources } from './models/AllocatedTaskResources';
export type { Allocation } from './models/Allocation';
export type { AllocationListStub } from './models/AllocationListStub';
export type { AllocationMetric } from './models/AllocationMetric';
export type { AllocDeploymentStatus } from './models/AllocDeploymentStatus';
export type { AllocStopResponse } from './models/AllocStopResponse';
export type { Attribute } from './models/Attribute';
export type { AutopilotConfiguration } from './models/AutopilotConfiguration';
export type { ChangeScript } from './models/ChangeScript';
export type { CheckRestart } from './models/CheckRestart';
export type { Constraint } from './models/Constraint';
export type { Consul } from './models/Consul';
export type { ConsulConnect } from './models/ConsulConnect';
export type { ConsulExposeConfig } from './models/ConsulExposeConfig';
export type { ConsulExposePath } from './models/ConsulExposePath';
export type { ConsulGateway } from './models/ConsulGateway';
export type { ConsulGatewayBindAddress } from './models/ConsulGatewayBindAddress';
export type { ConsulGatewayProxy } from './models/ConsulGatewayProxy';
export type { ConsulGatewayTLSConfig } from './models/ConsulGatewayTLSConfig';
export type { ConsulIngressConfigEntry } from './models/ConsulIngressConfigEntry';
export type { ConsulIngressListener } from './models/ConsulIngressListener';
export type { ConsulIngressService } from './models/ConsulIngressService';
export type { ConsulLinkedService } from './models/ConsulLinkedService';
export type { ConsulMeshConfigEntry } from './models/ConsulMeshConfigEntry';
export type { ConsulMeshGateway } from './models/ConsulMeshGateway';
export type { ConsulProxy } from './models/ConsulProxy';
export type { ConsulSidecarService } from './models/ConsulSidecarService';
export type { ConsulTerminatingConfigEntry } from './models/ConsulTerminatingConfigEntry';
export type { ConsulUpstream } from './models/ConsulUpstream';
export type { Context } from './models/Context';
export type { CSIControllerInfo } from './models/CSIControllerInfo';
export type { CSIInfo } from './models/CSIInfo';
export type { CSIMountOptions } from './models/CSIMountOptions';
export type { CSINodeInfo } from './models/CSINodeInfo';
export type { CSIPlugin } from './models/CSIPlugin';
export type { CSIPluginListStub } from './models/CSIPluginListStub';
export type { CSIPluginType } from './models/CSIPluginType';
export type { CSISecrets } from './models/CSISecrets';
export type { CSISnapshot } from './models/CSISnapshot';
export type { CSISnapshotCreateRequest } from './models/CSISnapshotCreateRequest';
export type { CSISnapshotCreateResponse } from './models/CSISnapshotCreateResponse';
export type { CSISnapshotListResponse } from './models/CSISnapshotListResponse';
export type { CSITopology } from './models/CSITopology';
export type { CSITopologyRequest } from './models/CSITopologyRequest';
export type { CSIVolume } from './models/CSIVolume';
export type { CSIVolumeAccessMode } from './models/CSIVolumeAccessMode';
export type { CSIVolumeAttachmentMode } from './models/CSIVolumeAttachmentMode';
export type { CSIVolumeCapability } from './models/CSIVolumeCapability';
export type { CSIVolumeCreateRequest } from './models/CSIVolumeCreateRequest';
export type { CSIVolumeExternalStub } from './models/CSIVolumeExternalStub';
export type { CSIVolumeListExternalResponse } from './models/CSIVolumeListExternalResponse';
export type { CSIVolumeListStub } from './models/CSIVolumeListStub';
export type { CSIVolumeRegisterRequest } from './models/CSIVolumeRegisterRequest';
export type { Deployment } from './models/Deployment';
export type { DeploymentAllocHealthRequest } from './models/DeploymentAllocHealthRequest';
export type { DeploymentPauseRequest } from './models/DeploymentPauseRequest';
export type { DeploymentPromoteRequest } from './models/DeploymentPromoteRequest';
export type { DeploymentState } from './models/DeploymentState';
export type { DeploymentUnblockRequest } from './models/DeploymentUnblockRequest';
export type { DeploymentUpdateResponse } from './models/DeploymentUpdateResponse';
export type { DesiredTransition } from './models/DesiredTransition';
export type { DesiredUpdates } from './models/DesiredUpdates';
export type { DispatchPayloadConfig } from './models/DispatchPayloadConfig';
export type { DNSConfig } from './models/DNSConfig';
export type { DrainMetadata } from './models/DrainMetadata';
export type { DrainSpec } from './models/DrainSpec';
export type { DrainStatus } from './models/DrainStatus';
export type { DrainStrategy } from './models/DrainStrategy';
export type { DriverInfo } from './models/DriverInfo';
export type { Duration } from './models/Duration';
export type { EphemeralDisk } from './models/EphemeralDisk';
export type { EvalOptions } from './models/EvalOptions';
export type { Evaluation } from './models/Evaluation';
export type { EvaluationStub } from './models/EvaluationStub';
export type { FieldDiff } from './models/FieldDiff';
export type { float32 } from './models/float32';
export type { float64 } from './models/float64';
export type { FuzzyMatch } from './models/FuzzyMatch';
export type { FuzzySearchRequest } from './models/FuzzySearchRequest';
export type { FuzzySearchResponse } from './models/FuzzySearchResponse';
export type { GaugeValue } from './models/GaugeValue';
export type { HostNetworkInfo } from './models/HostNetworkInfo';
export type { HostVolumeInfo } from './models/HostVolumeInfo';
export type { int32 } from './models/int32';
export type { int64 } from './models/int64';
export type { int8 } from './models/int8';
export type { Job } from './models/Job';
export type { JobACL } from './models/JobACL';
export type { JobChildrenSummary } from './models/JobChildrenSummary';
export type { JobDeregisterResponse } from './models/JobDeregisterResponse';
export type { JobDiff } from './models/JobDiff';
export type { JobDispatchRequest } from './models/JobDispatchRequest';
export type { JobDispatchResponse } from './models/JobDispatchResponse';
export type { JobEvaluateRequest } from './models/JobEvaluateRequest';
export type { JobListStub } from './models/JobListStub';
export type { JobPlanRequest } from './models/JobPlanRequest';
export type { JobPlanResponse } from './models/JobPlanResponse';
export type { JobRegisterRequest } from './models/JobRegisterRequest';
export type { JobRegisterResponse } from './models/JobRegisterResponse';
export type { JobRevertRequest } from './models/JobRevertRequest';
export type { JobScaleStatusResponse } from './models/JobScaleStatusResponse';
export type { JobsParseRequest } from './models/JobsParseRequest';
export type { JobStabilityRequest } from './models/JobStabilityRequest';
export type { JobStabilityResponse } from './models/JobStabilityResponse';
export type { JobSummary } from './models/JobSummary';
export type { JobValidateRequest } from './models/JobValidateRequest';
export type { JobValidateResponse } from './models/JobValidateResponse';
export type { JobVersionsResponse } from './models/JobVersionsResponse';
export type { LogConfig } from './models/LogConfig';
export type { MetricsSummary } from './models/MetricsSummary';
export type { MigrateStrategy } from './models/MigrateStrategy';
export type { Multiregion } from './models/Multiregion';
export type { MultiregionRegion } from './models/MultiregionRegion';
export type { MultiregionStrategy } from './models/MultiregionStrategy';
export type { Namespace } from './models/Namespace';
export type { NamespaceCapabilities } from './models/NamespaceCapabilities';
export type { NetworkResource } from './models/NetworkResource';
export type { Node } from './models/Node';
export type { NodeCpuResources } from './models/NodeCpuResources';
export type { NodeDevice } from './models/NodeDevice';
export type { NodeDeviceLocality } from './models/NodeDeviceLocality';
export type { NodeDeviceResource } from './models/NodeDeviceResource';
export type { NodeDiskResources } from './models/NodeDiskResources';
export type { NodeDrainUpdateResponse } from './models/NodeDrainUpdateResponse';
export type { NodeEligibilityUpdateResponse } from './models/NodeEligibilityUpdateResponse';
export type { NodeEvent } from './models/NodeEvent';
export type { NodeListStub } from './models/NodeListStub';
export type { NodeMemoryResources } from './models/NodeMemoryResources';
export type { NodePurgeResponse } from './models/NodePurgeResponse';
export type { NodeReservedCpuResources } from './models/NodeReservedCpuResources';
export type { NodeReservedDiskResources } from './models/NodeReservedDiskResources';
export type { NodeReservedMemoryResources } from './models/NodeReservedMemoryResources';
export type { NodeReservedNetworkResources } from './models/NodeReservedNetworkResources';
export type { NodeReservedResources } from './models/NodeReservedResources';
export type { NodeResources } from './models/NodeResources';
export type { NodeScoreMeta } from './models/NodeScoreMeta';
export type { NodeUpdateDrainRequest } from './models/NodeUpdateDrainRequest';
export type { NodeUpdateEligibilityRequest } from './models/NodeUpdateEligibilityRequest';
export type { number } from './models/number';
export type { ObjectDiff } from './models/ObjectDiff';
export type { OneTimeToken } from './models/OneTimeToken';
export type { OneTimeTokenExchangeRequest } from './models/OneTimeTokenExchangeRequest';
export type { OperatorHealthReply } from './models/OperatorHealthReply';
export type { ParameterizedJobConfig } from './models/ParameterizedJobConfig';
export type { PeriodicConfig } from './models/PeriodicConfig';
export type { PeriodicForceResponse } from './models/PeriodicForceResponse';
export type { PlanAnnotations } from './models/PlanAnnotations';
export type { PointValue } from './models/PointValue';
export type { Port } from './models/Port';
export type { PortMapping } from './models/PortMapping';
export type { PreemptionConfig } from './models/PreemptionConfig';
export type { QuotaLimit } from './models/QuotaLimit';
export type { Quotas } from './models/Quotas';
export type { QuotaSpec } from './models/QuotaSpec';
export type { RaftConfiguration } from './models/RaftConfiguration';
export type { RaftServer } from './models/RaftServer';
export type { RequestedDevice } from './models/RequestedDevice';
export type { RescheduleEvent } from './models/RescheduleEvent';
export type { ReschedulePolicy } from './models/ReschedulePolicy';
export type { RescheduleTracker } from './models/RescheduleTracker';
export type { Resources } from './models/Resources';
export type { RestartPolicy } from './models/RestartPolicy';
export type { SampledValue } from './models/SampledValue';
export type { ScalingEvent } from './models/ScalingEvent';
export type { ScalingPolicy } from './models/ScalingPolicy';
export type { ScalingPolicyListStub } from './models/ScalingPolicyListStub';
export type { ScalingRequest } from './models/ScalingRequest';
export type { SchedulerAlgorithm } from './models/SchedulerAlgorithm';
export type { SchedulerConfiguration } from './models/SchedulerConfiguration';
export type { SchedulerConfigurationResponse } from './models/SchedulerConfigurationResponse';
export type { SchedulerSetConfigurationResponse } from './models/SchedulerSetConfigurationResponse';
export type { SearchRequest } from './models/SearchRequest';
export type { SearchResponse } from './models/SearchResponse';
export type { ServerHealth } from './models/ServerHealth';
export type { Service } from './models/Service';
export type { ServiceCheck } from './models/ServiceCheck';
export type { ServiceRegistration } from './models/ServiceRegistration';
export type { SidecarTask } from './models/SidecarTask';
export type { Spread } from './models/Spread';
export type { SpreadTarget } from './models/SpreadTarget';
export type { Task } from './models/Task';
export type { TaskArtifact } from './models/TaskArtifact';
export type { TaskCSIPluginConfig } from './models/TaskCSIPluginConfig';
export type { TaskDiff } from './models/TaskDiff';
export type { TaskEvent } from './models/TaskEvent';
export type { TaskGroup } from './models/TaskGroup';
export type { TaskGroupDiff } from './models/TaskGroupDiff';
export type { TaskGroupScaleStatus } from './models/TaskGroupScaleStatus';
export type { TaskGroupSummary } from './models/TaskGroupSummary';
export type { TaskHandle } from './models/TaskHandle';
export type { TaskLifecycle } from './models/TaskLifecycle';
export type { TaskState } from './models/TaskState';
export type { Template } from './models/Template';
export type { Time } from './models/Time';
export type { uint } from './models/uint';
export type { uint16 } from './models/uint16';
export type { uint64 } from './models/uint64';
export type { uint8 } from './models/uint8';
export type { UpdateStrategy } from './models/UpdateStrategy';
export type { Variable } from './models/Variable';
export type { VariableItems } from './models/VariableItems';
export type { VariableMetadata } from './models/VariableMetadata';
export type { Vault } from './models/Vault';
export type { VolumeMount } from './models/VolumeMount';
export type { VolumeRequest } from './models/VolumeRequest';
export type { WaitConfig } from './models/WaitConfig';

export { AclService } from './services/AclService';
export { AllocationsService } from './services/AllocationsService';
export { DeploymentsService } from './services/DeploymentsService';
export { EnterpriseService } from './services/EnterpriseService';
export { EvaluationsService } from './services/EvaluationsService';
export { JobsService } from './services/JobsService';
export { MetricsService } from './services/MetricsService';
export { NamespacesService } from './services/NamespacesService';
export { NodesService } from './services/NodesService';
export { OperatorService } from './services/OperatorService';
export { PluginsService } from './services/PluginsService';
export { RegionsService } from './services/RegionsService';
export { ScalingService } from './services/ScalingService';
export { SearchService } from './services/SearchService';
export { StatusService } from './services/StatusService';
export { SystemService } from './services/SystemService';
export { VariablesService } from './services/VariablesService';
export { VolumesService } from './services/VolumesService';
